"""ajustando  users table

Revision ID: ef5be4d6e8cb
Revises: 8ea70889eab4
Create Date: 2025-08-03 17:48:32.769903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5be4d6e8cb'
down_revision: Union[str, Sequence[str], None] = '8ea70889eab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=False, server_dafault=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###
